# Neural Foundations

## Hebbian Learning Rule
> *Cells (neurons) that fire together, wire together.*

The mathematical update rule is:

$$
\Delta w = \eta \cdot x \cdot y
$$

Where:

- $\Delta w$ = change in weight
- $\eta$ = learning rate
- $x$ = input neuron activation
- $y$ = output neuron activation

Weight update equation:

$$
w_{new} = w_{old} + \eta \cdot x \cdot y
$$

In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 1, 0],
    [1, 1, 0],
    [1, 1, 0],
    [0, 0, 1]
])

print(f"Input X {X}")

# weights = np.random.randn(3) * 0.1
weights = np.ones(3)

learning_rate = 0.1

print(f"weights {weights}")

Input X [[1 1 0]
 [1 1 0]
 [1 1 0]
 [0 0 1]]
weights [1. 1. 1.]


### Define Neuron Output

The neuron output is a weighted sum:

$$
y = \sum_i w_i x_i
$$

In [3]:
def neuron_output(x, w):
    return np.dot(x, w)

In [4]:
# Weights increase when input and output activate together.
for epoch in range(5):
    for x in X:
        y = neuron_output(x, weights)
        weights += learning_rate * x * y

    print(f"Epoch {epoch+1} weights:", weights)

Epoch 1 weights: [1.728 1.728 1.1  ]
Epoch 2 weights: [2.985984 2.985984 1.21    ]
Epoch 3 weights: [5.15978035 5.15978035 1.331     ]
Epoch 4 weights: [8.91610045 8.91610045 1.4641    ]
Epoch 5 weights: [15.40702157 15.40702157  1.61051   ]


In [10]:
print(neuron_output(np.array([0, 0, 1]), weights))
print(neuron_output(np.array([1, 1, 0]), weights))

1.61051
30.814043149172736


It discovered dominant patterns automatically.

- Frequently co‑activated inputs gain stronger weights.
- The system learns correlations without labels.
- This is **unsupervised learning**.
----
- But there is no error correction
- It cannot distinguish useful vs useless features.


## Perceptron Model

The perceptron computes:

$$
y = \text{sign}(w_1x_1 + w_2x_2 + b)
$$

Weight update rule:

$$
w \leftarrow w + \eta (t - y)x
$$

Where:

- $x$ = input vector
- $w$ = weights
- $b$ = bias
- $t$ = target label
- $\eta$ = learning rate

In [ ]:
class Perceptron:
    def __init__(self, lr=0.1, epochs=10):
        self.lr = lr
        self.epochs = epochs

    def fit(self, X, y):
        self.weights = np.random.randn(X.shape[1]) * 0.1
        self.bias = 0

        for epoch in range(self.epochs):
            for xi, target in zip(X, y):
                output = self.predict(xi)
                update = self.lr * (target - output)
                self.weights += update * xi
                self.bias += update

    def predict(self, x):
        linear_output = np.dot(x, self.weights) + self.bias
        return 1 if linear_output >= 0 else 0